import "dotenv/config";
import dns from "dns/promises";
import { getODRequestsByDate, getStudentById, getAdvisors, getFacultyByEmail, getDepartmentRoles } from "./services/firestoreService.js";
import { sendEmail, sendAdminEmail, validateBrevoConfig } from "./services/emailService.js";
import { generateODEmail } from "./templates/emailTemplate.js";
import { generateAnalyticsEmail } from "./templates/analyticsEmailTemplate.js";

const MAX_emails = parseInt(process.env.MAX_EMAILS_PER_DAY) || parseInt(process.env.MAX_EMAIL_QUOTA) || 300;
const RATE_LIMIT_MS = parseInt(process.env.RATE_LIMIT_DELAY_MS) || 200;
const APP_TIMEZONE = process.env.APP_TIMEZONE || "UTC";
const ADMIN_EMAIL = process.env.ADMIN_EMAIL;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function validateEmailFormat(email) {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

async function checkMXRecord(email) {
  try {
    const domain = email.split("@")[1];
    if (!domain) return false;
    const mxRecords = await dns.resolveMx(domain);
    return mxRecords && mxRecords.length > 0;
  } catch {
    return false;
  }
}

function generateAdminReportHTML(timestamp, deliveryResults) {
  const successCount = deliveryResults.filter(r => r.status === "SUCCESS").length;
  const failureCount = deliveryResults.filter(r => r.status !== "SUCCESS").length;
  
  const rows = deliveryResults.map(r => `
    <tr style="background-color: ${r.status === 'SUCCESS' ? '#f0fdf4' : '#fef2f2'};">
      <td style="border: 1px solid #e5e7eb; padding: 8px;">${r.section}</td>
      <td style="border: 1px solid #e5e7eb; padding: 8px;">${r.email}</td>
      <td style="border: 1px solid #e5e7eb; padding: 8px; font-weight: bold; color: ${r.status === 'SUCCESS' ? '#166534' : '#991b1b'}">${r.status}</td>
      <td style="border: 1px solid #e5e7eb; padding: 8px; color: #374151;">${r.reason || '-'}</td>
    </tr>
  `).join('');

  return `
    <html>
      <body style="font-family: 'Segoe UI', sans-serif; line-height: 1.5; color: #111;">
        <div style="max-width: 800px; margin: 0 auto; padding: 20px;">
          
          <h2 style="color: #1e3a8a; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">Email Automation Report</h2>
          <p style="color: #6b7280;">Date: <strong>${timestamp}</strong></p>
          
          <div style="display: flex; gap: 20px; margin-bottom: 20px;">
             <div style="background: #dcfce7; padding: 15px; border-radius: 8px; flex: 1; text-align: center;">
               <strong style="display: block; font-size: 24px; color: #166534;">${successCount}</strong>
               <span style="color: #166534;">Sent Successfully</span>
             </div>
             <div style="background: #fee2e2; padding: 15px; border-radius: 8px; flex: 1; text-align: center;">
               <strong style="display: block; font-size: 24px; color: #991b1b;">${failureCount}</strong>
               <span style="color: #991b1b;">Failed</span>
             </div>
          </div>

          <table style="border-collapse: collapse; width: 100%; font-size: 14px;">
            <thead>
              <tr style="background: #f3f4f6; text-align: left;">
                <th style="border: 1px solid #e5e7eb; padding: 10px;">Context / Section</th>
                <th style="border: 1px solid #e5e7eb; padding: 10px;">Recipient</th>
                <th style="border: 1px solid #e5e7eb; padding: 10px;">Status</th>
                <th style="border: 1px solid #e5e7eb; padding: 10px;">Details / Reason</th>
              </tr>
            </thead>
            <tbody>${rows}</tbody>
          </table>
          
          <p style="margin-top: 30px; font-size: 12px; color: #9ca3af; text-align: center;">Generated by Email Automation System</p>
        </div>
      </body>
    </html>`;
}

async function main() {
  console.log("Starting Email Automation...");
  
  try {
    validateBrevoConfig();
  } catch (error) {
    console.error("Config Error:", error.message);
    process.exit(1);
  }

  const today = new Date().toLocaleDateString("en-CA", { timeZone: APP_TIMEZONE });
  console.log(`Processing date: ${today}`);

  let odRequests;
  try {
    odRequests = await getODRequestsByDate(today);
  } catch (error) {
    console.error("OD Request Fetch Error:", error.message);
    process.exit(1);
  }

  if (odRequests.length === 0) {
    console.log("No OD requests found today.");
    process.exit(0);
  }

  const groupedData = {};
  
  const allDepartments = new Set();

  for (const request of odRequests) {
    if (!request.studentId) continue;

    const student = await getStudentById(request.studentId);
    if (!student) continue;

    if (student.department) {
      allDepartments.add(student.department);
    }

    // Filter: Must be approved by HOD
    const hasHodApproval = request.approvalChain.some(
      approval => approval.role === 'hod' && approval.action === 'approved'
    );
    
    if (!hasHodApproval) continue;

    const department = student.department || "Unknown";
    const section = student.section || "Unknown";
    const groupKey = `${department}_${section}`;

    if (!groupedData[groupKey]) {
      groupedData[groupKey] = { department, section, students: [] };
    }

    groupedData[groupKey].students.push({
      ...student,
      reason: request.reason || "OD",
      event: request.type || request.reason || "Event",
      id: request.studentId
    });
  }

  const deliveryResults = [];
  let emailsSent = 0;
  const activeSections = Object.keys(groupedData);

  for (const groupKey of activeSections) {
    const group = groupedData[groupKey];
    const advisorMapping = await getAdvisors(group.department, group.section);
    
    if (!advisorMapping || !advisorMapping.advisorEmails?.length) {
      console.log(`No advisors for ${groupKey}`);
      deliveryResults.push({ section: groupKey, email: "N/A", status: "SKIPPED", reason: "No advisors mapped" });
      continue;
    }

    for (const email of advisorMapping.advisorEmails) {
      const result = { section: groupKey, email, status: "PENDING" };

      if (!validateEmailFormat(email) || !(await checkMXRecord(email)) || emailsSent >= MAX_emails) {
        let reason = "Invalid Format";
        if (emailsSent >= MAX_emails) reason = "Daily Quota Exceeded";
        else if (!(await checkMXRecord(email))) reason = "MX Record Missing";

        result.status = "FAILED";
        result.reason = reason;
        deliveryResults.push(result);
        continue;
      }

      try {
        const facultyDetails = await getFacultyByEmail(email);
        const teacherName = facultyDetails ? facultyDetails.name : "Class Advisor";
        
        const teacherProfile = { 
          name: teacherName, 
          section: group.section, 
          department: group.department 
        };
        const { subject, htmlContent } = generateODEmail(teacherProfile, group.students);
        await sendEmail(email, subject, htmlContent);
        
        result.status = "SUCCESS";
        emailsSent++;
        await sleep(RATE_LIMIT_MS);
      } catch (error) {
        result.status = "FAILED";
        result.reason = error.message;
      }
      deliveryResults.push(result);
    }
  }


  // --- Analytics Email Logic ---
  console.log("\n----------------------------------------");
  console.log("   DO Analytics Email Process");
  console.log("----------------------------------------");
  
  const departmentAnalytics = {};

  // Initialize analytics for all encountered departments
  for (const dept of allDepartments) {
    departmentAnalytics[dept] = {};
  }

  // Aggregate data by Department -> Section -> Count
  for (const groupKey of activeSections) {
    const group = groupedData[groupKey];
    const dept = group.department;
    const section = group.section;
    const count = group.students.length;

    if (!departmentAnalytics[dept]) {
      departmentAnalytics[dept] = {};
    }
    if (!departmentAnalytics[dept][section]) {
      departmentAnalytics[dept][section] = 0;
    }
    departmentAnalytics[dept][section] += count;
  }

  // Send Analytics Emails
  let analyticsSentCount = 0;
  for (const department of Object.keys(departmentAnalytics)) {
    try {
      console.log(`\nProcessing Department: ${department}`);
      const roles = await getDepartmentRoles(department);
      if (!roles) {
        console.log(`  > No roles found (Coordinator/HOD). Skipping.`);
        continue;
      }

      const analyticsData = departmentAnalytics[department];
      const { subject, htmlContent } = generateAnalyticsEmail(department, analyticsData);

      const recipients = [...roles.coordinatorEmails];
      if (roles.hodEmail) {
        recipients.push(roles.hodEmail);
      }

      const uniqueRecipients = [...new Set(recipients)]; // Remove duplicates
      
      if (uniqueRecipients.length === 0) {
        console.log(`  > No recipients found.`);
        continue;
      }

      console.log(`  > Recipients: ${uniqueRecipients.join(", ")}`);

      for (const email of uniqueRecipients) {
        if (!validateEmailFormat(email)) {
          console.log(`  > Invalid email format skipped: ${email}`);
          deliveryResults.push({
            section: `${department} (Analytics)`,
            email: email,
            status: "FAILED",
            reason: "Invalid Format"
          });
          continue;
        }

        try {
          await sendEmail(email, subject, htmlContent);
          console.log(`  > [SUCCESS] Email sent to ${email}`);
          analyticsSentCount++;
          deliveryResults.push({
            section: `${department} (Analytics)`,
            email: email,
            status: "SUCCESS"
          });
        } catch (error) {
           console.error(`  > [FAILED] could not send to ${email}:`, error.message);
           deliveryResults.push({
            section: `${department} (Analytics)`,
            email: email,
            status: "FAILED",
            reason: error.message
          });
        }
      }

    } catch (error) {
      console.error(`  > Error processing ${department}:`, error.message);
    }
  }


  console.log("\n----------------------------------------");
  console.log(`Execution Complete.`);
  console.log(`Advisor Emails Sent: ${emailsSent}`);
  console.log(`Analytics Emails Sent: ${analyticsSentCount}`);
  console.log("----------------------------------------");

  if (ADMIN_EMAIL) {
    try {
      const reportHTML = generateAdminReportHTML(today, deliveryResults);
      await sendAdminEmail(ADMIN_EMAIL, `Admin Report - ${today}`, reportHTML);
      console.log(`\nAdmin report sent to ${ADMIN_EMAIL}`);
    } catch (error) {
      console.error("\nFailed to send admin report:", error.message);
    }
  }

  process.exit(0);
}

main().catch(error => {
  console.error("Fatal Error:", error.message);
  process.exit(1);
});
